[2022-11-25 09:41:39,667] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.start manual__2022-11-25T09:41:25.537801+00:00 [queued]>
[2022-11-25 09:41:39,695] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.start manual__2022-11-25T09:41:25.537801+00:00 [queued]>
[2022-11-25 09:41:39,696] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 09:41:39,697] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-25 09:41:39,697] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-25 09:41:39,736] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): start> on 2022-11-25 09:41:25.537801+00:00
[2022-11-25 09:41:39,745] {taskinstance.py:1154} INFO - Dependencies not met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.start manual__2022-11-25T09:41:25.537801+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2022-11-25 09:41:39,749] {taskinstance.py:1154} INFO - Dependencies not met for <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.start manual__2022-11-25T09:41:25.537801+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2022-11-25 09:41:39,753] {standard_task_runner.py:52} INFO - Started process 7553 to run task
[2022-11-25 09:41:39,760] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GFA_Data_Engineering_Exam_dag01_ETL_pipeline', 'start', 'manual__2022-11-25T09:41:25.537801+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/MichalisKaratsioris_dag01.py', '--cfg-path', '/tmp/tmp8uxga33z', '--error-file', '/tmp/tmp58p1cvle']
[2022-11-25 09:41:39,762] {standard_task_runner.py:80} INFO - Job 78: Subtask start
[2022-11-25 09:41:39,773] {local_task_job.py:101} INFO - Task is not able to be run
[2022-11-25 09:41:39,926] {task_command.py:370} INFO - Running <TaskInstance: GFA_Data_Engineering_Exam_dag01_ETL_pipeline.start manual__2022-11-25T09:41:25.537801+00:00 [running]> on host c78bb2381ec5
[2022-11-25 09:41:40,096] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=GFA_Data_Engineering_Exam_dag01_ETL_pipeline
AIRFLOW_CTX_TASK_ID=start
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T09:41:25.537801+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T09:41:25.537801+00:00
[2022-11-25 09:41:40,101] {python.py:173} INFO - Done. Returned value was: Start of the work-flow!
[2022-11-25 09:41:40,193] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=GFA_Data_Engineering_Exam_dag01_ETL_pipeline, task_id=start, execution_date=20221125T094125, start_date=20221125T094139, end_date=20221125T094140
[2022-11-25 09:41:40,306] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-25 09:41:40,597] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
