[2022-11-16 18:03:27,957] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.load manual__2022-11-16T18:03:16.444243+00:00 [queued]>
[2022-11-16 18:03:27,970] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: MSSQL_connection.load manual__2022-11-16T18:03:16.444243+00:00 [queued]>
[2022-11-16 18:03:27,971] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 18:03:27,972] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-11-16 18:03:27,972] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-11-16 18:03:27,992] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): load> on 2022-11-16 18:03:16.444243+00:00
[2022-11-16 18:03:28,004] {standard_task_runner.py:52} INFO - Started process 204 to run task
[2022-11-16 18:03:28,011] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'MSSQL_connection', 'load', 'manual__2022-11-16T18:03:16.444243+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/pythonAirflowMSSQL.py', '--cfg-path', '/tmp/tmp6ocrxc8v', '--error-file', '/tmp/tmp4v9m0l_a']
[2022-11-16 18:03:28,014] {standard_task_runner.py:80} INFO - Job 35: Subtask load
[2022-11-16 18:03:28,094] {task_command.py:370} INFO - Running <TaskInstance: MSSQL_connection.load manual__2022-11-16T18:03:16.444243+00:00 [running]> on host 5036e10e6c0b
[2022-11-16 18:03:28,183] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MSSQL_connection
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2022-11-16T18:03:16.444243+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-16T18:03:16.444243+00:00
[2022-11-16 18:03:28,228] {base.py:68} INFO - Using connection ID '***_mssql' for task execution.
[2022-11-16 18:03:28,371] {sql.py:415} INFO - Done loading. Loaded a total of 4 rows
[2022-11-16 18:03:28,374] {python.py:173} INFO - Done. Returned value was: Data loading compete.
[2022-11-16 18:03:28,427] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=MSSQL_connection, task_id=load, execution_date=20221116T180316, start_date=20221116T180327, end_date=20221116T180328
[2022-11-16 18:03:28,464] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-16 18:03:28,506] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
